---
title: "Topatopa Project"
author: "Daniel K., Halina D., Peter M."
date: "8/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)
library(lubridate)
```

## Data 

```{r}
## Turns out starting with the slash takes us to the root directory and we can go down the file path from there... getting the dot dots to work was cool too though.

q1 <- read_csv("/courses/EDS214/topatopa/data/QuebradaCuenca1-Bisley.csv", na = c("-9999", ""))

q2 <- read_csv("/courses/EDS214/topatopa/data/QuebradaCuenca2-Bisley.csv", na = c("-9999", ""))

q3 <- read_csv("/courses/EDS214/topatopa/data/QuebradaCuenca3-Bisley.csv", na = c("-9999", ""))

mpr <- read_csv("/courses/EDS214/topatopa/data/RioMameyesPuenteRoto.csv", na = c("-9999", ""))
```

## Wrangling

```{r}
q1_clean <- q1 %>%
  janitor::clean_names() %>% 
  mutate(sample_date = lubridate::mdy(sample_date)) 

q2_clean <- q2 %>%
  janitor::clean_names() %>% 
  mutate(sample_date = lubridate::mdy_hm(sample_date)) 

q3_clean <- q3 %>%
  janitor::clean_names() %>% 
  mutate(sample_date = lubridate::mdy(sample_date)) 

mpr_clean <- mpr %>%
  janitor::clean_names() %>% 
  mutate(sample_date = lubridate::mdy(sample_date)) 
```

## Joining data frames

```{r}
combined_data <- q1_clean %>% 
  full_join(q2_clean) %>% 
  full_join(q3_clean) %>% 
  full_join(mpr_clean)

# could also use rbind()
```


## Visualizing SiO2 change over time

```{r}
sio2_all <- combined_data %>% 
  select(sample_date, si_o2) %>% 
  mutate(sample_date = year(sample_date)) %>% 
  rename(year = sample_date) %>% 
  group_by(year) %>% 
  summarize(si_o2 = mean(si_o2, na.rm = TRUE))

ggplot(sio2_all, aes(x = year, y = si_o2)) +
  geom_line()
  
```

## Grouped by site

```{r}
sio2_site <- combined_data %>% 
  select(sample_date, si_o2, sample_id) %>% 
  mutate(sample_date = year(sample_date)) %>% 
  rename(year = sample_date) %>% 
  group_by(year, sample_id) %>% 
  summarize(si_o2 = mean(si_o2, na.rm = TRUE))

ggplot(sio2_site, aes(x = year, y = si_o2)) +
  geom_line(aes(color = sample_id), size = 1) +
  labs(title = "SiO2 concentrations over time in four Luquillo Experimental \n Forest watershed study sites")
```

