---
title: "Topatopa Project"
author: "Daniel K., Halina D., Peter M."
date: "8/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)
library(lubridate)
```

## Data 

```{r}
q1 <- read_csv("/courses/EDS214/topatopa/data/QuebradaCuenca1-Bisley.csv", na = c("-9999", ""))

q2 <- read_csv("/courses/EDS214/topatopa/data/QuebradaCuenca2-Bisley.csv", na = c("-9999", ""))

q3 <- read_csv("/courses/EDS214/topatopa/data/QuebradaCuenca3-Bisley.csv", na = c("-9999", ""))

mpr <- read_csv("/courses/EDS214/topatopa/data/RioMameyesPuenteRoto.csv", na = c("-9999", ""))
```

## Wrangling

```{r}
q1_clean <- q1 %>%
  janitor::clean_names() %>% 
  mutate(sample_date = lubridate::mdy(sample_date)) 

q2_clean <- q2 %>%
  janitor::clean_names() %>% 
  mutate(sample_date = lubridate::mdy_hm(sample_date)) 

q3_clean <- q3 %>%
  janitor::clean_names() %>% 
  mutate(sample_date = lubridate::mdy(sample_date)) 

mpr_clean <- mpr %>%
  janitor::clean_names() %>% 
  mutate(sample_date = lubridate::mdy(sample_date)) 
```

## Joining data frames

```{r}
combined_data <- q1_clean %>% 
  full_join(q2_clean) %>% 
  full_join(q3_clean) %>% 
  full_join(mpr_clean)

# could also use rbind()
```

